INSERT INTO equipo (sku, nombre, tipo, descripcion, sede) VALUES
('EQP001', 'Laptop Lenovo ThinkPad', 'Portátil', 'Laptop para uso administrativo', 'Sede Lima'),
('EQP002', 'Laptop Lenovo ThinkPad', 'Portátil', 'Laptop para uso administrativo', 'Sede Arequipa'),
('EQP003', 'Laptop Dell Inspiron', 'Portátil', 'Laptop de oficina', 'Sede Trujillo'),
('EQP004', 'Monitor Samsung 24"', 'Monitor', 'Monitor Full HD 24 pulgadas', 'Sede Lima'),
('EQP005', 'Monitor Samsung 24"', 'Monitor', 'Monitor Full HD 24 pulgadas', 'Sede Cusco'),
('EQP006', 'CPU HP ProDesk 400', 'PC Escritorio', 'Equipo fijo para tareas contables', 'Sede Lima'),
('EQP007', 'CPU HP ProDesk 400', 'PC Escritorio', 'Equipo fijo para tareas contables', 'Sede Piura'),
('EQP008', 'Impresora HP LaserJet', 'Impresora', 'Impresora monocromática', 'Sede Lima'),
('EQP009', 'Impresora HP LaserJet', 'Impresora', 'Impresora monocromática', 'Sede Chiclayo'),
('EQP010', 'Router TP-Link Archer', 'Red', 'Router inalámbrico para oficinas pequeñas', 'Sede Lima'),
('EQP011', 'Router TP-Link Archer', 'Red', 'Router inalámbrico para oficinas pequeñas', 'Sede Tacna'),
('EQP012', 'Switch Cisco SG300', 'Red', 'Switch de 24 puertos', 'Sede Arequipa'),
('EQP013', 'Tablet Samsung Galaxy Tab', 'Tablet', 'Tablet para movilidad de personal técnico', 'Sede Lima'),
('EQP014', 'Tablet Samsung Galaxy Tab', 'Tablet', 'Tablet para movilidad de personal técnico', 'Sede Ica'),
('EQP015', 'All in One Lenovo', 'Todo en Uno', 'Equipo compacto para recepcionistas', 'Sede Lima'),
('EQP016', 'All in One Lenovo', 'Todo en Uno', 'Equipo compacto para recepcionistas', 'Sede Cajamarca'),
('EQP017', 'Proyector Epson X41', 'Proyector', 'Proyector para presentaciones', 'Sede Lima'),
('EQP018', 'Proyector Epson X41', 'Proyector', 'Proyector para presentaciones', 'Sede Trujillo'),
('EQP019', 'Servidor Dell PowerEdge', 'Servidor', 'Servidor de archivos interno', 'Sede Lima'),
('EQP020', 'Servidor Dell PowerEdge', 'Servidor', 'Servidor de archivos interno', 'Sede Arequipa'),
('EQP021', 'Escáner Canon Lide', 'Escáner', 'Escáner para documentación', 'Sede Lima'),
('EQP022', 'Escáner Canon Lide', 'Escáner', 'Escáner para documentación', 'Sede Cusco'),
('EQP023', 'Teclado Logitech K120', 'Periférico', 'Teclado USB', 'Sede Lima'),
('EQP024', 'Teclado Logitech K120', 'Periférico', 'Teclado USB', 'Sede Chiclayo'),
('EQP025', 'Mouse Logitech M90', 'Periférico', 'Mouse óptico con cable', 'Sede Lima'),
('EQP026', 'Mouse Logitech M90', 'Periférico', 'Mouse óptico con cable', 'Sede Piura'),
('EQP027', 'UPS APC 700VA', 'Energía', 'Respaldo de energía', 'Sede Lima'),
('EQP028', 'UPS APC 700VA', 'Energía', 'Respaldo de energía', 'Sede Trujillo'),
('EQP029', 'Webcam Logitech C270', 'Periférico', 'Cámara para videollamadas', 'Sede Lima'),
('EQP030', 'Webcam Logitech C270', 'Periférico', 'Cámara para videollamadas', 'Sede Arequipa');

INSERT INTO usuario (nombre, correo, contrasena, rol) VALUES
('Juan Pérez', 'juan@example.com', 'juanperez1234', 'ADMIN'),
('María Gómez', 'maria@example.com', 'mariagomez5050', 'ADMIN'),
('Carlos Ruiz', 'carlos@example.com', 'carlos123', 'ADMIN');

INSERT INTO reporte_mantenimiento (fecha, descripcion, equipo_id, tecnico_id, tipo_mantenimiento, estado) VALUES
('2025-06-01', 'Revisión general del equipo', 1, 1, 'Preventivo', 'En Proceso'),
('2025-06-03', 'Cambio de pantalla rota', 3, 2, 'Correctivo', 'Recibido'),
('2025-06-05', 'Actualización de software', 5, 1, 'Preventivo', 'Finalizado'),
('2025-06-07', 'Mantenimiento de red', 10, 3, 'Correctivo', 'En Proceso'),
('2025-06-09', 'Limpieza interna del CPU', 6, 2, 'Preventivo', 'Recibido'),
('2025-06-10', 'Reemplazo de fuente de poder', 7, 3, 'Correctivo', 'Finalizado'),
('2025-06-11', 'Problema con impresión continua', 8, 1, 'Correctivo', 'En Proceso'),
('2025-06-12', 'Chequeo por lentitud del sistema', 15, 2, 'Correctivo', 'Recibido'),
('2025-06-13', 'Mantenimiento a tablet', 13, 1, 'Preventivo', 'Finalizado'),
('2025-06-14', 'Revisión de conectividad', 11, 2, 'Correctivo', 'Recibido'),
('2025-06-15', 'Sustitución de switch dañado', 12, 3, 'Correctivo', 'En Proceso'),
('2025-06-16', 'Revisión de disco duro', 2, 2, 'Correctivo', 'Finalizado'),
('2025-06-17', 'Configuración de escáner nuevo', 22, 3, 'Instalación', 'Recibido'),
('2025-06-18', 'Mantenimiento a UPS por sobrecalentamiento', 28, 1, 'Correctivo', 'Finalizado'),
('2025-06-19', 'Actualización de drivers', 4, 2, 'Preventivo', 'En Proceso');
